"""Add latitude and longitude columns to pickup_dropoff_locations

Revision ID: 126081d87d4c
Revises: 3aef92c10b8a
Create Date: 2025-07-26 09:46:13.584256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126081d87d4c'
down_revision = '3aef92c10b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_dropoff_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.drop_column('GPSystem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_dropoff_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GPSystem', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
