"""Fix route_id naming

Revision ID: 5b1b41234db9
Revises: 126081d87d4c
Create Date: 2025-07-26 12:27:53.900276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1b41234db9'
down_revision = '126081d87d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_dropoff_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        
        # Give the FK constraint a name to avoid "Constraint must have a name" error
        batch_op.create_foreign_key(
            'fk_pickupdropoff_route',  # ← constraint name
            'routes',                  # ← target table
            ['route_id'],              # ← source column
            ['id']                     # ← target column
        )

        batch_op.drop_column('routeid')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_dropoff_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routeid', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'routes', ['routeid'], ['id'])
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
