"""Make route_id non-nullable in pickup_dropoff_locations

Revision ID: dbcb4a6e5269
Revises: 5b1b41234db9
Create Date: 2025-07-26 12:33:52.356336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcb4a6e5269'
down_revision = '5b1b41234db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_dropoff_locations', schema=None) as batch_op:
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_dropoff_locations', schema=None) as batch_op:
        batch_op.alter_column('route_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
